language: erlang

os: linux

dist: xenial

before_install:
  - pip install --user cpp-coveralls coveralls-merge

script: make && make xref && make test

after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json

otp_release:
  - 19.3
  - 22.3
  - 23.0
